In [2]:
import numpy as np

In [3]:
pip freeze 

absl-py==0.8.0
alabaster==0.7.12
altgraph==0.16.1
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.2
asn1crypto==0.24.0
astor==0.8.0
astroid==2.2.5
astropy==3.1.2
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.6.0
backcall==0.1.0
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
bcrypt==3.1.7
beautifulsoup4==4.7.1
bitarray==0.8.3
bkcharts==0.2
bleach==3.1.0
bokeh==1.0.4
boto==2.49.0
bottle==0.12.18
bottle-websocket==0.2.9
Bottleneck==1.2.1
certifi==2019.6.16
cffi==1.12.2
chardet==3.0.4
Click==7.0
cloudpickle==0.8.0
clyent==1.2.2
colorama==0.4.1
comtypes==1.1.7
conda==4.7.11
conda-build==3.17.8
conda-package-handling==1.4.1
conda-verify==3.1.1
contextlib2==0.5.5
cryptography==2.6.1
cx-Oracle==7.3.0
cycler==0.10.0
Cython==0.29.6
cytoolz==0.9.0.1
dask==1.1.4
decorator==4.4.0
defusedxml==0.5.0
distributed==1.26.0
docutils==0.14
EasyProcess==0.2.7
Eel==0.12.2
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.10
Flask==1.0.2
future==0.17.1
gast==

In [4]:
import numpy as np


In [6]:
print(np.__version__)

1.16.2


In [7]:
#numpy documentaion
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['l:/Users/rohan/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'l:/Users/rohan/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['l:/Users/rohan/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'l:/U

In [8]:
#zeros arry
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
python -c "print('wdsad')"

SyntaxError: invalid syntax (<ipython-input-9-1e0773562bc2>, line 1)

In [10]:
#modify zero array

z=np.zeros(10)
z[7]=67
print(z)


[ 0.  0.  0.  0.  0.  0.  0. 67.  0.  0.]


In [14]:
# range
z=np.arange(10,21)
print(z)

[10 11 12 13 14 15 16 17 18 19 20]


In [18]:
#pass single one argument in arange

z=np.arange(50)
z=z[::-1]# reverse 
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [20]:
# ct\rate 3X3

z=np.arange(9).reshape(3,3)#generate in matix
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
#find indices of non zero element

z=np.nonzero([1,2,3,5,0,8,0,0])
print(z)

(array([0, 1, 2, 3, 5], dtype=int64),)


In [22]:
#create 3X3 identity matrix
z=np.eye(5)#identity matrix
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
#display 3X3x3 random values
z=np.random.random((3,3,3))
            #array of 3x3x3
print(z)


[[[0.91089283 0.75899707 0.17929624]
  [0.03090735 0.15380595 0.14780382]
  [0.82877655 0.80506424 0.20122988]]

 [[0.07989837 0.69851865 0.65140949]
  [0.69612682 0.46460069 0.26089559]
  [0.43380302 0.74447926 0.8356028 ]]

 [[0.18978355 0.40929753 0.40994265]
  [0.45143176 0.34934418 0.13089059]
  [0.33148062 0.25761935 0.150985  ]]]


In [24]:
#10X10 matrix

z=np.random.random((10,10)) 
zmin,zmax=z.min(),z.max()
print(zmin,zmax)

0.016969021368176462 0.9940172232382455


In [25]:
#find mean

z=np.random.random(30)
c=z.mean()
print(c)

0.5938126139435472


In [26]:
# ones value
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [28]:
#find output
0* np.nan
np.nan==np.nan
np.inf>np.nan
np.nan-np.nan
0.3==3*0.1

False

In [30]:
0* np.nan

nan

In [32]:
np.nan==np.nan

False

In [33]:
np.inf>np.nan

False

In [34]:
np.nan-np.nan

nan

In [36]:
0.3==3*0.1

False

In [42]:
#craete 5X5 vales 1234 in digonal format

z=np.diag(1+np.arange(4),k=0)
print(z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [44]:
# craete 8X8 checkboard pattren
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [45]:
#shape array
print(np.unravel_index(100,(6,7,8)))
#Returns
    -------
    unraveled_coords : tuple of ndarray


(1, 5, 4)


In [49]:
help(np.unravel_index)


Help on built-in function unravel_index in module numpy:

unravel_index(...)
    unravel_index(indices, shape, order='C')
    
    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.
    
    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``shape``. Before version 1.6.0,
        this function accepted just one index value.
    shape : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    
        .. versionchanged:: 1.16.0
            Renamed from ``dims`` to ``shape``.
    
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.
    
        .. versionadded:: 1.6.0
    
    Returns
    -------
    unraveled_coords : tuple of ndarray
        Each array in the tuple has the same shape as the ``in

In [51]:
# craete 8X8 checkboard pattren
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [52]:
#craete cus datatype that descirdes as four sunsinged (RGBA)

color=(np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                 ("b",np.ubyte,1),
                 ("a",np.ubyte,1)
                ]))
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [57]:
#multipy in numpy package


a=np.array([(1,2,3),(3,6,4)],dtype=int)
b=np.array([(1,2,3),(2,4,6)],dtype=float)

print(np.multiply(a,b))

[[ 1.  4.  9.]
 [ 6. 24. 24.]]


In [55]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081]


In [58]:
print(a==b)

[[ True  True  True]
 [False False False]]


In [59]:
z=np.array([[1,2,3],[4,5,6]],dtype='float')
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]


In [60]:
# array from tulple
z=np.array((1,2,3,4))
print(z)#array

[1 2 3 4]


In [64]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [65]:
# create a constant array of omplex type
d=np.full((3,4),6,dtype='complex')# complex numbe
print(d)

[[6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j]]


In [66]:
arra=np.array([[1,3,5],[123,32,23],[34,234,234]])
print(arra)

[[  1   3   5]
 [123  32  23]
 [ 34 234 234]]


In [74]:
new=arra.reshape(1,1,2)
print(new)

ValueError: cannot reshape array of size 9 into shape (1,1,2)

In [83]:
#indexing in numpy
arr=np.array([[1,2,3,4],
             [-2,3,4,2],
              [3.4,3,6,-8],
              [4,5,3,5]
             ])
##slicing array
temp=arr[:3,::2]
print(temp)




[[ 1.   3. ]
 [-2.   4. ]
 [ 3.4  6. ]]


In [82]:
#int array inndexing
temp=np.array([[1,2,3,4],[6,7,8,9]])
print(temp)

[[1 2 3 4]
 [6 7 8 9]]


# open cv
